name: check

on:
  push: {}

jobs:
  check-cpu:
    runs-on: ubuntu-latest-large
    steps:
      - name: Check CPU count
        run: |
          echo "Number of CPUs: $(nproc)"
          echo "CPU info:"
          lscpu
